service: erp
frameworkVersion: "3"
plugins:
  - serverless-plugin-typescript
provider:
  name: aws
  runtime: nodejs18.x
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "dynamodb:PutItem"
            - "dynamodb:Get*"
            - "dynamodb:Scan*"
            - "dynamodb:UpdateItem"
            - "dynamodb:Query"
            - "dynamodb:DeleteItem"
          Resource: arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/ErpTable
  environment:
    TABLE_NAME: { Ref: ErpTable }

functions:
  createCompany:
    handler: src/handlers/createCompany.main
    events:
      - httpApi:
          path: /
          method: post
  getCompany:
    handler: src/handlers/getCompany.main
    events:
      - httpApi:
          path: /{name}
          method: get
  getCompanies:
    handler: src/handlers/getCompanies.main
    events:
      - httpApi:
          path: /
          method: get
  updateCompany:
    handler: src/handlers/updateCompany.main
    events:
      - httpApi:
          path: /{name}
          method: put
  deleteCompany:
    handler: src/handlers/deleteCompany.main
    events:
      - httpApi:
          path: /{name}
          method: delete
resources:
  Resources:
    ErpTable:
      Type: "AWS::DynamoDB::Table"
      Properties:
        AttributeDefinitions:
          - AttributeName: "PK"
            AttributeType: "S"
          - AttributeName: "SK"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "PK"
            KeyType: "HASH"
          - AttributeName: "SK"
            KeyType: "RANGE"
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        TableName: ErpTable
